blog/urls.py
from	django.urls	import	path
from blog import	views
app_name	=	'blog'
urlpatterns	=	[
		path('',	views.post_list,	name='post_list'),
		path('',	views.PostListView.as_view(),	name='post_list'),
		path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
		path('<int:post_id>/share/',views.post_share,	name='post_share'),
		path('/contact',	views.contact,	name='contact')
]

mysite/urls.py
from	django.urls	import	path, include
from	django.contrib	import	admin
urlpatterns	=	[path('admin/',	admin.site.urls),
				path('',	include('blog.urls',	namespace='blog')),
]

blog/models.py
from	django.db	import	models
from	django.utils	import	timezone
from	django.contrib.auth.models	import	User
from	django.urls	import	reverse

class	PublishedManager(models.Manager):
	def	get_queryset(self):
		return	super(PublishedManager,self).get_queryset().filter(status='published')

class	Post(models.Model):
    STATUS_CHOICES	=	(
					('draft',	'Draft'),
					('published',	'Published'),)
    title	=	models.CharField(max_length=250)
    slug	=	models.SlugField(max_length=250,unique_for_date='publish')
    author	=	models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body	=	models.TextField()
    publish	=	models.DateTimeField(default=timezone.now)
    created	=	models.DateTimeField(auto_now_add=True)
    updated	=	models.DateTimeField(auto_now=True)
    status	=	models.CharField(max_length=10,	choices=STATUS_CHOICES,default='draft')
    objects	=	models.Manager()
    published	= PublishedManager()
    def	get_absolute_url(self):
        return	reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

class	Meta:
	ordering	=	('-publish',)
def	__str__(self):
	return	self.title

class	Comment(models.Model):	
				post	=	models.ForeignKey(Post,
																													on_delete=models.CASCADE,
																													related_name='comments')
				name	=	models.CharField(max_length=80)	
				email	=	models.EmailField()	
				body	=	models.TextField()	
				created	=	models.DateTimeField(auto_now_add=True)	
				updated	=	models.DateTimeField(auto_now=True)	
				active	=	models.BooleanField(default=True)	
				class	Meta:	
								ordering	=	('created',)	
				def	__str__(self):	
								return	'Comment	by	{}	on	{}'.format(self.name,	self.post)

blog/forms.py
from	django	import	forms
from	.models	import	Comment
class	EmailPostForm(forms.Form):
	name	=	forms.CharField(max_length=25)
	email	=	forms.EmailField()
	to	=	forms.EmailField()
	comments	=	forms.CharField(required=False,widget=forms.Textarea)

class	CommentForm(forms.ModelForm):
	class	Meta:
		model	=	Comment
		fields	=	('name',	'email',	'body')

blog/views.py
from django.shortcuts import render
from	django.core.paginator	import	Paginator,	EmptyPage, PageNotAnInteger
from	django.views.generic	import	ListView
from	django.core.mail	import	send_mail

# Create your views here.
from	django.shortcuts	import	render,	get_object_or_404
from	.models	import	Post, Comment
from	.forms	import	EmailPostForm, CommentForm

def contact(request):
    return	render(request,'blog/post/contact.html')

class	PostListView(ListView):
	queryset	=	Post.published.all()
	context_object_name	=	'posts'
	paginate_by	=	3
	template_name	=	'blog/post/list.html'

def	post_list(request):
	object_list	=	Post.published.all()
	paginator	=	Paginator(object_list,	5)	#	5	posts	in	each	page
	page	=	request.GET.get('page')
	try:
			posts	=	paginator.page(page)
	except	PageNotAnInteger:
	#	If	page	is	not	an	integer	deliver	the	first	page
			posts	=	paginator.page(1)
	except	EmptyPage:
	#	If	page	is	out	of	range	deliver	last	page	of	results
	    posts	=	paginator.page(paginator.num_pages)

	return	render(request,'blog/post/list.html',{'posts':	posts})
def	post_detail(request,	year,	month,	day,	post):
    post	=	get_object_or_404(Post,	slug=post,status='published',publish__year=year,publish__month=month,publish__day=day)
    comments	=	post.comments.filter(active=True)
    new_comment	=	None
    if	request.method	==	'POST':
        comment_form	=	CommentForm(data=request.POST)
        if	comment_form.is_valid():								
            new_comment	=	comment_form.save(commit=False)
            new_comment.post	=	post
            new_comment.save()
    else:
        comment_form	=	CommentForm()
    return	render(request,'blog/post/detail.html',{'post':	post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

def	post_share(request,	post_id):
    sent=False
    post	=	get_object_or_404(Post,	id=post_id,	status='published')
    form	=	EmailPostForm(request.POST)
    if	request.method	==	'POST':
        if	form.is_valid():
            cd	=	form.cleaned_data
            post_url	=	request.build_absolute_uri(post.get_absolute_url())
            subject	=	'{}	({})	recommends	you	reading	"{}"'.format(cd['name'],	cd['email'],	post.title)
            message	=	'Read	"{}"	at	{}\n\n{}\'s	comments:	{}'.format(post.title,	post_url,	cd['name'],	cd['comments'])
            send_mail(subject,	message,	'sanketrathod040@gmail.com',[cd['to']])
            sent	=	True
        else:
            form	=	EmailPostForm()
    return	render(request,	'blog/post/share.html',	{'post':post,'form':form,'sent':sent})

blog/templates/blog/base.html
{%	load	static	%}
<!DOCTYPE	html>
<html>
	<style>
		* {box-sizing: border-box;}
		body { 
		  margin: 0;
		  font-family: Arial, Helvetica, sans-serif;
		}
		
		.header {
		  overflow: hidden;
		  background-color: #008080;
		  padding: 20px 10px;
		}
		
		.header a {
		  float: left;
		  color: black;
		  text-align: center;
		  padding: 12px;
		  text-decoration: none;
		  font-size: 18px; 
		  line-height: 25px;
		  border-radius: 4px;
		}
		
		.header a.logo {
		  font-size: 25px;
		  font-weight: bold;
		}
		
		.header a:hover {
		  background-color: #ddd;
		  color: black;
		}
		
		.header a.active {
		  background-color: dodgerblue;
		  color: white;
		}
		
		.header-right {
		  float: right;
		}
		
		@media screen and (max-width: 500px) {
		  .header a {
			float: none;
			display: block;
			text-align: left;
		  }
		  
		  .header-right {
			float: none;
		  }
		}
		</style>
<head>
	<title>{%	block	title	%}{%	endblock	%}</title>
		<link	href="{%	static	"css/blog.css"	%}"	rel="stylesheet">
</head>
<body>
	<div class="header">
		<a href="{% url	'blog:post_list'	%}" class="logo">Daily Blog</a>
		<div class="header-right">
		  <a class="active" href="{% url	'blog:post_list'	%}">Home</a>
		  <a href="{% url	'blog:contact'	%}">Contact</a>
		  <a href="#about">About</a>
		</div>
	  </div>
	  
	<div id="content">
	{%	block	content	%}
			{%	endblock	%}
	</div>
	<div 	id="sidebar">
	</div>
</body>
</html>

blog/templates/blog/post/contact.html
{%	extends	"blog/base.html"	%}
{%	block	content	%}
<h2>Working hours:
    Monday – Saturday: 9:00 – 20:00
    Sunday: Closed</h2>
<h2>Cell: +91 35462 37783
    +91 32858 63729
Tel  : 370-7230 6266
</h2>
<h2>Email:
 gdskuyiu@gmail.com</h2>
    <h2>ahdgkgsdghl@gmail.com</h2>
{%	endblock	%}

blog/templates/blog/post/detail.html
{%	extends	"blog/base.html"	%}
{%	block	title	%}{{	post.title	}}{%	endblock	%}
{%	block	content	%}
<style>
	h1 {
		width:500px;
		margin: 0 auto;
		background: gray;
		text-align: center;
	}
</style>
	<h1 >{{	post.title	}}</h1>
	<p	class="date">
	<b>Published	{{	post.publish	}}	by	{{	post.author	}}</b>
	</p>
		{{	post.body|linebreaks	}}
	<br>
	<p>
		<a	href="{% url	'blog:post_share'	post.id	%}">Share	this	post</a>
	</p>
	<br>
	{%	for	comment	in	comments	%}
		<div	class="comment">
				<p	class="info">
						Comment	{{	forloop.counter	}}	by	{{	comment.name	}}
						{{	comment.created	}}
				</p>
				{{	comment.body|linebreaks	}}
		</div>
{%	empty	%}
		<p>There	are	no	comments	yet.</p>
		{%	if	new_comment	%}
		<h2>Your	comment	has	been	added.</h2>
		{%	else	%}
		<h2>Add	a	new	comment</h2>
		<form	action="."	method="post">
				{{	comment_form.as_p	}}
				{%	csrf_token	%}
				<p><input	type="submit"	value="Add	comment"></p>
		</form>
{%	endif	%}
{%	endfor	%}
	
{%	endblock	%}

blog/templates/blog/post/list.html
{%	extends	"blog/base.html"	%}
{%	block	content	%}
	{%	for	post	in	posts	%}
	<h2>
	<a	href="{{	post.get_absolute_url	}}">
	{{	post.title	}}
	</a>
	</h2>
	<p	class="date">
	<b>Published	{{	post.publish	}}	by	{{	post.author	}}</b>
	</p>
	<div>
		{{	post.body|truncatewords:50|linebreaks	}}
	</div>
	<br>
	{%	endfor	%}
	{%	include	"pagination.html"	with	page=page_obj	%}

{%	endblock	%}

blog/templates/blog/post/share.html
{%	extends	"blog/base.html"	%}
{%	block	title	%}Share	a	post{%	endblock	%}
{%	block	content	%}
		{%	if	sent	%}
				<h1>E-mail	successfully	sent</h1>
				<p>
						"{{	post.title	}}"	was	successfully	sent	to	{{	form.cleaned_data.to	}}.
				</p>
		{%	else	%}
				<h1>Share	"{{	post.title	}}"	by	e-mail</h1>
				<form	action="."	method="post">
						{{	form.as_p	}}
						{%	csrf_token	%}
						<input	type="submit"	value="Send	e-mail">
				</form>
		{%	endif	%}
{%	endblock	%}

blog/templates/pagination.html
<div	class="pagination">
	<span	class="step-links">
	{%	if	page.has_previous	%}
	<a	href="?page={{	page.previous_page_number	}}">Previous</a>
	{%	endif	%}
	<span	class="current">
	Page	{{	page.number	}}	of	{{	page.paginator.num_pages	}}.
	</span>
	{%	if	page.has_next	%}
	<a	href="?page={{	page.next_page_number	}}">Next</a>
	{%	endif	%}
		</span>
</div>